#
#
#
#
####################
### scrape
####################
#
#_meta.script_name: scrape-news
#
#force_update: True
#
##categories: all
#skip_existing: True
#
#skip_confirm: True
#
#
##################################
### sanitize-news
##################################
#
#_meta.script_name: sanitize-news
#_meta.script_name: nlp-news
#
#categories: general
#limit: 1
#
#

#date: '20-08-07'
#sanitize_workers: 24
#timeout: None
#
#
########################
### present-notion
########################

#_meta.script_name: present-notion
##
##resume: True
#num_workers: 0
#
#parents: ['usual']
#
##skip_confirm: True
#
#remove_existing: False
#
##skip_existing: False
#
##resume: True

#
#parents: ['news_table']
#
##table_id: 766aa794-f3f3-4a6a-a696-c4212590311a
#
#
####################
### new table
####################
#
##_meta.script_name: new-notion-table
#
##parents: ['new_table']
#
#
#
#

####################
### clean prompts (dataset formatting)
####################

#_meta.script_name: clean-prompts
#_meta.script_name: loc-prompts

blobroot: /home/fleeb/Downloads

#accept: yes

#loc: ch

promptpath: interface/prompts/prompts-{loc}.jsonl
completedpath: interface/completed/completed_{loc}.jsonl

articleroot: /home/fleeb/workspace/local_data/nnn/global-news-headlines



