#
#
#
#
####################
### scrape
####################
#
#_meta.script_name: scrape-news
#
#force_update: True
#
##categories: all
#skip_existing: True
#
##skip_confirm: True
#
#
##################################
### sanitize-news
##################################
#
_meta.script_name: sanitize-news
#
#categories: general
#limit: 1
#
#

#date: '20-08-07'
<<<<<<< HEAD
sanitize_workers: 24
=======
#sanitize_workers: 24
>>>>>>> c8a12f75cc5af40e9c65af4b82729e2261dba956
timeout: None
#
#
########################
### present-notion
########################

<<<<<<< HEAD
#_meta.script_name: present-notion
=======
_meta.script_name: present-notion
>>>>>>> c8a12f75cc5af40e9c65af4b82729e2261dba956
#
#resume: True
#num_workers: 0

parents: ['usual']

#remove_existing: False

#skip_existing: False

resume: True

#
#parents: ['news_table']
#
##table_id: 766aa794-f3f3-4a6a-a696-c4212590311a
#
#
####################
### new table
####################
#
##_meta.script_name: new-notion-table
#
##parents: ['new_table']
#
#
#
#
